### ISSUE TITLE
Complete user guide 

### ISSUE THREAD

**Issue by ZhangYiJiang** [CS2103AUG2016-W10-C4/main#3]
https://hackmd.io/GYBghgpgjAzAnAYwLQCYwoKxICwDYBG+ScEKyK2MwCA7ACYAcIouQA==?edit

- [x] Add list of commands 
- [x] Discuss command format 
- [x] Include brief summary of functionality 
- [x] Installation instruction and quickstart guide

**Comment by ZhangYiJiang** [comment]
Fixed by #10
