### ISSUE TITLE
Figure out the tagging system 

### ISSUE THREAD

**Issue by ZhangYiJiang** [CS2103AUG2016-W10-C4/main#33]
We need to discuss how the tagging system would work. A few things - 
- [x] Can tags be mass editable? Are they case sensitive? 
- [x] How many tags per task? What order will they come in? 
- [x] How to allow them to be edited both en mass and on individual tasks? 

From there we need to modify the code 
- [x] Logic needs new argument and commands to support 
- [x] Model need new classes to back the tag data 
- [x] Modify find command to include tagging

**Comment by ZhangYiJiang** [comment]
Proposal: 

### `tag` command - editing the tags on one or more tasks 

- Positional argument (optional) - INDEX. If this is not specified the command will apply the edit to all tasks (TODO: all **visible** tasks or all tasks?) 

Named arguments: 

- delete (`/d NAME`) - deletes the tag
- edit (`/e ORIGINAL NEW`) - changes the tag from the original to the new tag 
- add (`/a NAME`) - adds a tag

### Implementation details: 

- **Tags are shared between all tasks** - If two task shares the same tag, the tag would reference the same tag object. 

- Tags are uniquely identified by their name

- Tag names can contain any character except comma, and cannot be whitespace only, empty or null 

- Tags are case insensitive - **TODO**: Discuss issue with display and readability 

- Storage - Can tags be stored as references?

**Comment by xdrawks** [comment]
I actually think that tags should be lower cased only though. there isn't many use case for tags like CS3230  vs cs3230, is there?

**Comment by ZhangYiJiang** [comment]
Right, hence case insensitivity. My bigger concern is readability, since capital letters aid reading, although that's not a huge concern. Oh, and should we have a max number of tags?

**Comment by xdrawks** [comment]
oh right didn't see carefully @.@

**Comment by xdrawks** [comment]
suggestion to follow hashtag rules, though you mean you allow things like "hello world"?

**Comment by ZhangYiJiang** [comment]
Yeah. You mean you don't want spaces? Because hashtags are actually case sensitive, as people use #TitleCase when they write hash tags to distinguish words. I don't find that particularly appealing, to be honest.

**Comment by xdrawks** [comment]
hmm just listing out some ideas bah, but I don't really fancy long tags either (hard to fit into design too!)

**Comment by ZhangYiJiang** [comment]
True. Limit the user to say 20 char or something I guess. Tags should be short and sweet. This would not be very usable if we don't implement #11 though
