### ISSUE TITLE
Implement the help command 

### ISSUE THREAD

**Issue by ZhangYiJiang** [CS2103AUG2016-W10-C4/main#42]
## Design: 

- [x] Decide on `help` command format - done, we will use `help` for listing all commands and `help COMMAND` and `COMMAND --help` for getting detailed help info about a specific command 
- [x] How should help messages be sent from Logic to UI? Through Event or `CommandResult` object? 

## Implementation:
 
- [x] Add a function on `BaseCommand` to generate help text from individual argument objects 
- [x] Implement function(s) on the `BaseCommand` interface to retrieve the help string
- [x] Implement the `help` command itself 
- [x] Create the interface between UI and Logic component
